parser: babel-eslint
plugins:
  - prettier
  - flowtype
extends:
  - airbnb
  - prettier
  - prettier/react
env:
  es6: true
  browser: true
  node: true
parserOptions:
  ecmaVersion: 6
  ecmaFeatures:
    jsx: true
    experimentalObjectRestSpread: true
rules:
  no-underscore-dangle: 0
  react/jsx-filename-extension: 0
  prettier/prettier:
    - error
    - trailingComma: es5
      singleQuote: true
